print("|  Welcom To Calculator App  |\n")
NB1 = int ( input ("Enter The First Number  : ") )
NB2 = int ( input ("Enter The Second Number : ") )                    
print("|  ------------------------------  |")
print("Adding : " + str(NB1+NB2))
print("Subtract5 : " + str(NB1-NB2))
print("Multiply : " + str(NB1*NB2))
print("Divide : " + str(NB1/NB2))
print("Modulus : " + str(NB1%NB2))
